### ISSUE TITLE
AbstractEntity - Invalid argument supplied for foreach

### ISSUE THREAD

**Issue by xtrasmal** [toin0u/DigitalOceanV2#84]
I'm using 0.5.* dev version, because of the nextWindow error that's fixed in that version. Still I'm having problems running the droplet service

composer.json:
```yaml
    "require": {
        "php": ">=5.3.3",
        "symfony/symfony": "2.6.*",
        "toin0u/digitalocean-v2": "0.5.*@dev",
        "kriswallsmith/buzz": "~0.10",
        "guzzle/guzzle": "~3.7",
        "guzzlehttp/guzzle" : "~5.0"
    },
```

The terrors:
```
CRITICAL - Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: 
"Warning: Invalid argument supplied for foreach()" at 
/var/www/chuck/symfony/vendor/toin0u/digitalocean-v2/src/Entity/AbstractEntity.php line 67 
```
```
'2', 'Invalid argument supplied for foreach()', 
'/var/www/chuck/symfony/vendor/toin0u/digitalocean-v2/src/Entity/AbstractEntity.php', '67', 
array('parameters' => null))
in vendor/toin0u/digitalocean-v2/src/Entity/AbstractEntity.php at line 67
```

services.yml
```yaml
parameters:
    #digital ocean
    do.class.factory:           DigitalOceanV2\DigitalOceanV2
    do.class.adapter:           DigitalOceanV2\Adapter\GuzzleAdapter

# widgets
    # controllers
    widgets.controller: Chuck\NorrisBundle\Controller\WidgetController

services:

# digital ocean
    do.adapter:
        class: %do.class.adapter%
        public: false
        arguments: ["%digital_ocean_api%"]
    do.factory:
        class: %do.class.factory%
        arguments: [@do.adapter]
```

and for the sake of simplicity; 
```php
<?php namespace Chuck\NorrisBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class DropletController extends Controller
{
    public function indexAction()
    {
        $droplet = $this->container->get( 'do.factory' )->droplet();
        $droplets = $droplet->getAll();

        return $this->render( 'NorrisBundle:Widget:index.html.twig', [
            'droplets' => $droplets
        ] );
    }

}

```

Does anybody know how to go from here, without having to hack around in this broken library?
